### PR TITLE
#2670 interactive message bug fix

### LINKED ISSUE #2670: Interactive Message: Context message text
**Describe the bug**
When sending an interactive template message using a dynamic interactive message the message is sent, and when the user replies by clicking the button, the context message shown is an unparsed message 

**Screenshots**
Chat screen

image

**Interactive message**
image
Interactive message in flow
image

### PR DESCRIPTION
**Pull request by mohitgusain**
#2670 

1. Parse message body for the sheet interactive messages

**Note** - After fixed added, I checked all the interactive messages and working fine

### CODE REVIEW

File: lib/glific/flows/contact_action.ex [hunk 1]
```diff
@@ -92,7 +92,7 @@ defmodule Glific.Flows.ContactAction do
 
     with {false, context} <- has_loops?(context, body, messages) do
       attrs = %{
-        body: body,
+        body: MessageVarParser.parse(body, message_vars),
```
Comment (pankaj-ag) [inline lib/glific/flows/contact_action.ex:95]: @mohitgusain are you sure this is the fix ? Because I think we are changing the body in the create_and_send_message function also.

Please confirm and explain that and then we can merge.

**Review by pankaj-ag — CHANGES_REQUESTED** [review]

File: lib/glific/flows/contact_action.ex (hunk 1 above)
Comment (mohitgusain) [reply lib/glific/flows/contact_action.ex:95]: yes @pankaj-ag I am sure about the fix. While using the inactive message from the sheet, the body was not saved into the DB table in the correct format. In the body, the variable was getting saved into DB. Attaching a screenshot for reference.

image

Comment (pankaj-ag) [reply lib/glific/flows/contact_action.ex:95]: Okay let's chat about this

**Review by pankaj-ag — APPROVED** [review]
